import { chromium } from 'playwright'
const b = await chromium.launch(); const page = await (await b.newContext({ viewport: { width: 1440, height: 900 } })).newPage()
const B='http://127.0.0.1:8000'; const s=(ms)=>new Promise(r=>setTimeout(r,ms))
await page.goto(B + '/login'); await s(800)
await page.locator('.demo-acc button').filter({ hasText: /^Admin/ }).click(); await page.waitForURL(/dashboard/); await s(800)
await page.goto(B + '/app/users'); await s(1000)
await page.getByRole('button', { name: 'Create user' }).first().click()
await page.fill('#un', 'Test Analyst'); await page.fill('#ue', 'analyst@example.org'); await page.selectOption('#ur', 'investigator'); await page.fill('#up', 'Analyst2026')
await page.locator('.modal-foot .btn.primary').click(); await s(1200)
await page.screenshot({ path: 'e2e/dbg1.png' })
await page.getByRole('button', { name: 'Sign out' }).click(); await s(1200)
console.log('after signout', page.url())
await page.goto(B + '/login'); await s(800)
await page.fill('#email', 'analyst@example.org'); await page.fill('#password', 'Analyst2026'); await page.getByRole('button', { name: 'Sign in', exact: true }).click(); await s(1500)
console.log('after login', page.url()); await page.screenshot({ path: 'e2e/dbg2.png' })
await b.close()
